"""Shell tab-completion for the ascii-magic CLIs (issue #5).

``ascii-magic completion bash`` (or ``zsh``) prints a static completion
script generated by introspecting each subcommand's argparse parser —
subcommand names, per-command flags, and the value choices of enum flags,
with filename completion as the fallback. Because the script is static,
tab presses never pay Python startup cost.

Install:
    ascii-magic completion bash > ~/.local/share/bash-completion/completions/ascii-magic
    # or, in ~/.bashrc / ~/.zshrc:
    eval "$(ascii-magic completion bash)"    # bash
    eval "$(ascii-magic completion zsh)"     # zsh
"""

from __future__ import annotations

import argparse
import sys
from typing import Dict, List, Optional, Tuple

# Standalone console scripts that share the same completion function.
_SCRIPT_ALIASES = {
    "image-to-ascii": "image",
    "colorize-ascii": "colorize",
    "text-to-ascii": "text",
    "ascii-magic-greet": "greet",
    "ascii-magic-web": "web",
    "ascii-magic-video": "video",
}

Spec = Tuple[List[str], Dict[str, List[str]], Dict[str, "Spec"]]


def _collect(parser: argparse.ArgumentParser) -> Spec:
    """(flags, {flag: choice values}, {subcommand: nested spec})."""
    flags: List[str] = []
    choices: Dict[str, List[str]] = {}
    subs: Dict[str, Spec] = {}
    for action in parser._actions:
        if isinstance(action, argparse._SubParsersAction):
            for name, sub in action.choices.items():
                subs[name] = _collect(sub)
            continue
        if not action.option_strings:
            continue
        flags.extend(action.option_strings)
        if action.choices:
            vals = [str(c) for c in action.choices]
            for s in action.option_strings:
                choices[s] = vals
    return flags, choices, subs


def _specs() -> Dict[str, Spec]:
    # webapp is not imported: it needs the [web] extra; its two flags are static.
    from .colorize_ascii import build_arg_parser as colorize_parser
    from .greet import build_arg_parser as greet_parser
    from .image_to_ascii import build_arg_parser as image_parser
    from .text_to_ascii import build_arg_parser as text_parser
    from .video import build_arg_parser as video_parser

    specs = {
        "colorize": _collect(colorize_parser()),
        "image": _collect(image_parser()),
        "text": _collect(text_parser()),
        "greet": _collect(greet_parser()),
        "video": _collect(video_parser()),
        "web": (["--host", "--port", "-h", "--help"], {}, {}),
        "completion": (["-h", "--help"], {"shell": ["bash", "zsh"]}, {}),
    }
    return specs


def _prev_case(choices: Dict[str, List[str]], indent: str) -> List[str]:
    if not choices:
        return []
    out = [f'{indent}case "$prev" in']
    for flag in sorted(choices):
        vals = " ".join(choices[flag])
        out.append(f'{indent}    {flag}) COMPREPLY=( $(compgen -W "{vals}" -- "$cur") ); return 0 ;;')
    out.append(f"{indent}esac")
    return out


def _flags_block(flags: List[str], indent: str) -> List[str]:
    words = " ".join(sorted(set(flags)))
    return [
        f'{indent}if [[ "$cur" == -* ]]; then',
        f'{indent}    COMPREPLY=( $(compgen -W "{words}" -- "$cur") )',
        f"{indent}    return 0",
        f"{indent}fi",
    ]


def bash_script() -> str:
    specs = _specs()
    cmd_names = " ".join(sorted(specs))

    lines = [
        "# ascii-magic shell completion - generated by `ascii-magic completion bash`",
        "_ascii_magic() {",
        "    local cur prev cmd base",
        '    cur="${COMP_WORDS[COMP_CWORD]}"',
        '    prev="${COMP_WORDS[COMP_CWORD-1]}"',
        '    cmd=""',
        "    base=1",
        '    case "${COMP_WORDS[0]##*/}" in',
    ]
    for script, cmd in sorted(_SCRIPT_ALIASES.items()):
        lines.append(f'        {script}) cmd="{cmd}"; base=0 ;;')
    lines += [
        "    esac",
        '    if [ -z "$cmd" ]; then',
        '        if [ "$COMP_CWORD" -le 1 ]; then',
        f'            COMPREPLY=( $(compgen -W "{cmd_names}" -- "$cur") )',
        "            return 0",
        "        fi",
        '        cmd="${COMP_WORDS[1]}"',
        "    fi",
        '    case "$cmd" in',
    ]

    for name in sorted(specs):
        flags, choices, subs = specs[name]
        lines.append(f"        {name})")
        if name == "completion":
            lines.append('            COMPREPLY=( $(compgen -W "bash zsh" -- "$cur") ); return 0')
            lines.append("            ;;")
            continue
        if subs:
            lines.append('            local sub=""')
            lines.append('            if [ "$COMP_CWORD" -gt "$((base+1))" ]; then sub="${COMP_WORDS[$((base+1))]}"; fi')
            lines.append('            if [ "$COMP_CWORD" -eq "$((base+1))" ]; then')
            lines.append(f'                COMPREPLY=( $(compgen -W "{" ".join(sorted(subs))}" -- "$cur") )')
            lines.append("                return 0")
            lines.append("            fi")
            lines.append('            case "$sub" in')
            for sub_name in sorted(subs):
                s_flags, s_choices, _ = subs[sub_name]
                lines.append(f"                {sub_name})")
                lines += _prev_case(s_choices, " " * 20)
                lines += _flags_block(s_flags, " " * 20)
                lines.append("                    ;;")
            lines.append("            esac")
        else:
            lines += _prev_case(choices, " " * 12)
            lines += _flags_block(flags, " " * 12)
        lines.append("            ;;")

    all_names = " ".join(["ascii-magic"] + sorted(_SCRIPT_ALIASES))
    lines += [
        "    esac",
        "    return 0",
        "}",
        f"complete -o default -F _ascii_magic {all_names}",
        "",
    ]
    return "\n".join(lines)


def zsh_script() -> str:
    # zsh runs the bash-style function through its bash compatibility layer.
    return (
        "# ascii-magic shell completion (zsh) - generated by `ascii-magic completion zsh`\n"
        "autoload -U +X compinit && compinit\n"
        "autoload -U +X bashcompinit && bashcompinit\n"
        + bash_script()
    )


def build_arg_parser() -> argparse.ArgumentParser:
    ap = argparse.ArgumentParser(
        prog="ascii-magic completion",
        description="Print a shell tab-completion script for the ascii-magic commands.",
        epilog='Install with e.g.: eval "$(ascii-magic completion bash)" in ~/.bashrc',
    )
    ap.add_argument("shell", choices=["bash", "zsh"], help="Target shell")
    return ap


def main(argv: Optional[List[str]] = None) -> int:
    args = build_arg_parser().parse_args(argv)
    sys.stdout.write(bash_script() if args.shell == "bash" else zsh_script())
    return 0


if __name__ == "__main__":
    sys.exit(main())
